# ---------- Build ----------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .
RUN dotnet publish "ITIRR.Web/ITIRR.Web.csproj" -c Release -o /app/publish

# ---------- Nginx ----------
FROM nginx:alpine

COPY --from=build /app/publish/wwwroot /usr/share/nginx/html
COPY nginx.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]