# ---------- Build ----------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .
RUN dotnet publish "ITIRR.Web/ITIRR.Web.csproj" -c Release -o /app/publish

# ---------- Serve with Nginx ----------
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

COPY --from=build /app/publish/wwwroot .

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]